// agent-notes: { ctx: "Frontend API client for uploading resumes, fetching analysis history, and exporting reports", deps: [], state: "active", last: "anti@2026-08-29" }

const API_BASE_URL = import.meta.env.VITE_API_URL || '/api';

function getAuthHeaders() {
  const token = localStorage.getItem('sb_token') || sessionStorage.getItem('sb_token');
  const user = JSON.parse(localStorage.getItem('sb_user') || '{}');
  return {
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...(user?.id ? { 'x-user-id': user.id } : {})
  };
}

/**
 * Uploads a resume file (or text) and optional job description for AI evaluation.
 */
export async function analyzeResumeFile({ file, resumeText, jobDescription = '', targetRole = '' }) {
  const formData = new FormData();

  if (file) {
    formData.append('resume', file);
  }
  if (resumeText) {
    formData.append('resumeText', resumeText);
  }
  if (jobDescription) {
    formData.append('jobDescription', jobDescription);
  }
  if (targetRole) {
    formData.append('targetRole', targetRole);
  }

  const headers = getAuthHeaders();

  const res = await fetch(`${API_BASE_URL}/resume/analyze`, {
    method: 'POST',
    headers,
    body: formData
  });

  if (!res.ok) {
    const errData = await res.json().catch(() => ({}));
    const errorMsg = errData.error || errData.message || `Analysis request failed with status ${res.status}`;
    throw new Error(errorMsg);
  }

  return await res.json();
}

/**
 * Retrieves past resume analysis history
 */
export async function getResumeHistory() {
  const res = await fetch(`${API_BASE_URL}/resume/history`, {
    headers: {
      'Content-Type': 'application/json',
      ...getAuthHeaders()
    }
  });

  if (!res.ok) {
    return { success: true, history: [] };
  }
  return await res.json();
}

/**
 * Fetches a single past analysis record by ID
 */
export async function getResumeRecord(id) {
  const res = await fetch(`${API_BASE_URL}/resume/history/${id}`, {
    headers: {
      'Content-Type': 'application/json',
      ...getAuthHeaders()
    }
  });

  if (!res.ok) {
    throw new Error('Failed to load resume scan details.');
  }
  return await res.json();
}

/**
 * Deletes a past analysis record
 */
export async function deleteResumeRecord(id) {
  const res = await fetch(`${API_BASE_URL}/resume/history/${id}`, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json',
      ...getAuthHeaders()
    }
  });
  return await res.json();
}

/**
 * Exports and downloads formatted analysis summary as a text/markdown file
 */
export function downloadAnalysisReport(result, fileName = 'Resume_Analysis') {
  if (!result) return;
  const content = [
    `# AI Resume Analysis Report`,
    `File: ${fileName}`,
    `Date: ${new Date().toLocaleDateString()}`,
    ``,
    `## Executive Scores`,
    `- Overall Score: ${result.overall_score}/100`,
    `- ATS Compatibility: ${result.ats_compatibility?.score || result.overall_score}/100`,
    `- Keyword Alignment: ${result.keyword_gaps?.match_percentage || 70}%`,
    ``,
    `## Key Strengths`,
    ...(result.strengths || []).map((s) => `- ${s}`),
    ``,
    `## ATS & Parsing Observations`,
    ...(result.ats_compatibility?.formatting_issues || []).map((item) => `- Formatting: ${item}`),
    ...(result.ats_compatibility?.missing_standard_sections || []).map((sec) => `- Missing Section: ${sec}`),
    ...(result.ats_compatibility?.parsing_risks || []).map((risk) => `- Parsing Risk: ${risk}`),
    ``,
    `## Keyword Gap Analysis`,
    `- Missing Keywords: ${(result.keyword_gaps?.missing_keywords || []).join(', ') || 'None'}`,
    `- Matched Keywords: ${(result.keyword_gaps?.matched_keywords || []).join(', ') || 'None'}`,
    ``,
    `## Bullet Point Recommendations & Rewrites`,
    ...(result.rewrite_suggestions || []).map((r, i) =>
      `### Recommendation #${i + 1}\n- **Original:** ${r.original}\n- **AI Suggested:** ${r.suggested}\n- **Reason:** ${r.reason}\n`
    ),
    ``,
    `## Section-by-Section Critiques`,
    ...(result.section_feedback || []).map((sf) => `### ${sf.section}\n${sf.feedback}\n`),
    ``,
    `---`,
    `Generated by SkillBridge AI • https://my-project-eta-sepia.vercel.app/`
  ].join('\n');

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${fileName.replace(/\.[^/.]+$/, '')}_Analysis.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export const resumeApi = {
  analyzeResumeFile,
  getResumeHistory,
  getResumeRecord,
  deleteResumeRecord,
  downloadAnalysisReport
};

export default resumeApi;
