import React from 'react';
import { 
  Map, 
  BookOpen, 
  ExternalLink, 
  CheckCircle2, 
  HelpCircle,
  Award
} from 'lucide-react';
import { generateRoadmap } from '../utils/aiSimulator';

export default function LearningRoadmap({ profile, missingSkillsList }) {
  // If roadmap was generated by job analyzer, use those missing skills, otherwise fall back to profile gap simulation
  const defaultMissing = missingSkillsList.length > 0 
    ? missingSkillsList 
    : ["React.js", "Git", "Node.js"].filter(s => !profile.skills.includes(s));

  const [roadmap, setRoadmap] = React.useState([]);
  const [expandedWeek, setExpandedWeek] = React.useState(0);
  const [checkedTopics, setCheckedTopics] = React.useState({});

  React.useEffect(() => {
    const data = generateRoadmap(defaultMissing);
    setRoadmap(data);
    
    // Initialize checked topics
    const initialChecked = {};
    data.forEach(week => {
      week.topics.forEach((topic, idx) => {
        initialChecked[`${week.id}-${idx}`] = false;
      });
    });
    setCheckedTopics(initialChecked);
    setExpandedWeek(0);
  }, [profile, missingSkillsList, defaultMissing]);

  const handleToggleTopic = (weekId, topicIdx) => {
    const key = `${weekId}-${topicIdx}`;
    setCheckedTopics(prev => ({
      ...prev,
      [key]: !prev[key]
    }));
  };

  const getWeekProgress = (week) => {
    const topics = week.topics;
    const checkedCount = topics.filter((_, idx) => checkedTopics[`${week.id}-${idx}`]).length;
    return topics.length > 0 ? Math.round((checkedCount / topics.length) * 100) : 0;
  };

  const getOverallProgress = () => {
    const totalTopics = roadmap.reduce((acc, w) => acc + w.topics.length, 0);
    const checkedCount = Object.values(checkedTopics).filter(Boolean).length;
    return totalTopics > 0 ? Math.round((checkedCount / totalTopics) * 100) : 0;
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Map className="w-5 h-5 text-accent-purple" /> Personalized Learning Roadmap
          </h2>
          <p className="text-xs text-gray-400">Step-by-step weekly guide configured by AI to bridge your matching skill gaps</p>
        </div>

        {roadmap.length > 0 && (
          <div className="glass rounded-xl px-4 py-2 flex items-center gap-3 shrink-0 self-start md:self-center border border-accent-purple/20">
            <div>
              <span className="text-[10px] uppercase font-bold text-gray-400 block">Total Progress</span>
              <span className="text-sm font-extrabold text-white">{getOverallProgress()}%</span>
            </div>
            <div className="w-24 h-2 bg-gray-800 rounded-full overflow-hidden">
              <div 
                className="h-full bg-gradient-to-r from-accent-purple to-accent-pink transition-all duration-500" 
                style={{ width: `${getOverallProgress()}%` }}
              />
            </div>
          </div>
        )}
      </div>

      {roadmap.length === 0 ? (
        <div className="glass rounded-xl p-12 text-center flex flex-col items-center justify-center space-y-4 border-dashed border-gray-800 min-h-[300px]">
          <Award className="w-12 h-12 text-accent-emerald animate-bounce" />
          <div className="space-y-1">
            <h4 className="text-md font-semibold text-white">Zero Gaps Found!</h4>
            <p className="text-xs text-gray-400">Your profile skills match all target roles perfectly. Try pasting a more complex job description!</p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Timeline navigation (Left) */}
          <div className="space-y-3 lg:col-span-2">
            {roadmap.map((week, index) => {
              const isExpanded = expandedWeek === index;
              const progress = getWeekProgress(week);
              
              return (
                <div 
                  key={week.id} 
                  className={`glass rounded-xl transition-all border overflow-hidden ${isExpanded ? 'border-accent-purple/30 shadow-lg shadow-accent-purple/5' : 'border-gray-800 hover:border-gray-700'}`}
                >
                  {/* Accordion header */}
                  <button 
                    onClick={() => setExpandedWeek(isExpanded ? -1 : index)}
                    className="w-full text-left p-4 flex items-center justify-between gap-4"
                  >
                    <div className="space-y-1 overflow-hidden">
                      <span className="text-[10px] uppercase font-bold text-accent-purple tracking-wider block">{week.week}</span>
                      <h4 className="text-sm font-semibold text-white truncate leading-relaxed">{week.title}</h4>
                    </div>
                    
                    <div className="flex items-center gap-3 shrink-0">
                      {progress === 100 ? (
                        <CheckCircle2 className="w-5 h-5 text-accent-emerald" />
                      ) : (
                        <span className="text-xs font-semibold px-2 py-0.5 rounded bg-gray-800 text-gray-400">{progress}%</span>
                      )}
                    </div>
                  </button>

                  {/* Accordion contents */}
                  {isExpanded && (
                    <div className="px-4 pb-5 pt-1 border-t border-gray-800/50 space-y-4">
                      {/* Checkbox tasks */}
                      <div className="space-y-2">
                        <span className="text-[10px] uppercase font-bold text-gray-400 block tracking-wider mb-2">Weekly Objectives</span>
                        {week.topics.map((topic, tIdx) => {
                          const topicKey = `${week.id}-${tIdx}`;
                          const isChecked = checkedTopics[topicKey];
                          
                          return (
                            <label 
                              key={tIdx} 
                              className="flex items-start gap-2.5 p-2 rounded-lg hover:bg-white/5 transition-colors cursor-pointer text-xs"
                            >
                              <input 
                                type="checkbox"
                                checked={isChecked || false}
                                onChange={() => handleToggleTopic(week.id, tIdx)}
                                className="mt-0.5 w-4 h-4 accent-accent-purple rounded bg-gray-900 border-gray-700 text-accent-purple focus:ring-0 focus:ring-offset-0"
                              />
                              <span className={`leading-relaxed text-gray-300 ${isChecked ? 'line-through text-gray-500' : ''}`}>
                                {topic}
                              </span>
                            </label>
                          );
                        })}
                      </div>

                      {/* Course recommendation in week */}
                      <div className="space-y-2 pt-2">
                        <span className="text-[10px] uppercase font-bold text-gray-400 block tracking-wider">Recommended Study Material</span>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          {week.resources.map((res, rIdx) => (
                            <a 
                              key={rIdx} 
                              href={res.link} 
                              target="_blank" 
                              rel="noreferrer"
                              className="p-3 rounded-lg border border-gray-800 hover:border-accent-purple/20 bg-white/5 hover:bg-accent-purple/5 transition-colors flex items-center justify-between text-xs"
                            >
                              <div className="overflow-hidden pr-2">
                                <span className="font-semibold text-white block truncate">{res.name}</span>
                                <span className="text-[10px] text-gray-500 mt-0.5">{res.provider}</span>
                              </div>
                              <ExternalLink className="w-3.5 h-3.5 text-gray-500 hover:text-white shrink-0" />
                            </a>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Guidelines / Help (Right) */}
          <div className="space-y-6">
            <div className="glass rounded-xl p-5 space-y-4">
              <h3 className="text-sm font-semibold text-white flex items-center gap-1.5">
                <HelpCircle className="w-4.5 h-4.5 text-accent-purple" /> How to Study?
              </h3>
              <div className="space-y-3.5 text-xs leading-relaxed text-gray-300">
                <p>
                  1. **Spend 2 Hours Daily**: Dedicate consistent blocks to reading docs and writing code.
                </p>
                <p>
                  2. **Code as you Learn**: Don't just watch videos. Create a folder locally and test every snippet you read.
                </p>
                <p>
                  3. **Clear Milestones**: Check off topics in the list as you master them. You will see your dashboard statistics update in real-time.
                </p>
              </div>
            </div>

            {/* Courses overview list */}
            <div className="glass rounded-xl p-5 space-y-4">
              <h3 className="text-sm font-semibold text-white flex items-center gap-1.5">
                <BookOpen className="w-4.5 h-4.5 text-accent-purple" /> Learning Resource Links
              </h3>
              <div className="space-y-3">
                <div className="text-xs space-y-1">
                  <span className="font-semibold text-white block">FreeCodeCamp YouTube Portal</span>
                  <p className="text-[10px] text-gray-400">Excellent 10-hour full courses on Git, React, Express, and Databases.</p>
                </div>
                <hr className="border-gray-800" />
                <div className="text-xs space-y-1">
                  <span className="font-semibold text-white block">MDN Web Docs Reference</span>
                  <p className="text-[10px] text-gray-400">The gold standard reference guide for JS APIs, CSS variables, and HTML elements.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
